// dashboard-data.js
// Generated by tools/build-dashboard-data.ps1
// Summary indicators only. Do not store sensitive request details here.

window.managementDashboardData = {
  "meta": {
    "title": "لوحة المتابعة الإدارية",
    "version": "v1.0",
    "lastUpdated": "2026-05-17",
    "dataSource": "Excel / CSV exports",
    "note": "هذه اللوحة تعرض مؤشرات مجمعة فقط ولا تحتوي على تفاصيل الطلبات."
  },
  "summary": {
    "openRequests": 9,
    "overdueRequests": 0,
    "criticalRequests": 0,
    "pendingInvoices": 0,
    "expiringLicenses": 0,
    "bottleneckDepartment": "تقنية المعلومات"
  },
  "it": {
    "label": "تقنية المعلومات",
    "open": 9,
    "critical": 0,
    "overdue": 0,
    "closed": 8,
    "averageAgeDays": 8,
    "status": "محدث"
  },
  "maintenance": {
    "label": "الصيانة",
    "open": 0,
    "critical": 0,
    "overdue": 0,
    "closed": 0,
    "averageAgeDays": 0,
    "status": "بانتظار البيانات"
  },
  "hr": {
    "label": "الموارد البشرية",
    "pendingLeave": 0,
    "pendingPermission": 0,
    "pendingBusinessTrip": 0,
    "pendingWorkPermit": 0,
    "totalPending": 0,
    "status": "بانتظار البيانات"
  },
  "procurement": {
    "label": "المشتريات",
    "inProgress": 0,
    "pendingApproval": 0,
    "overdue": 0,
    "status": "بانتظار البيانات"
  },
  "finance": {
    "label": "المالية",
    "pendingInvoices": 0,
    "pendingContractorPayments": 0,
    "overduePayments": 0,
    "status": "بانتظار البيانات"
  },
  "licenses": {
    "label": "الرخص",
    "expiringIn30Days": 0,
    "expiringIn60Days": 0,
    "expired": 0,
    "status": "بانتظار البيانات"
  },
  "bottlenecks": [
    {
      "department": "تقنية المعلومات",
      "open": 9,
      "overdue": 0,
      "critical": 0,
      "score": 9,
      "level": "متوسط",
      "reason": "There are 9 open IT tickets based on the export file."
    }
  ],
  "alerts": [
    "There are 9 open IT tickets.",
    "Maintenance data is waiting for first export file.",
    "HR data is waiting for first export file.",
    "Finance and license data are not added yet."
],
  "dataQuality": {
    "it": {
      "status": "جزئي",
      "message": "IT file is readable, but these columns are missing: priority, due_date, department."
    },
    "maintenance": {
      "status": "غير متوفر",
      "message": "Maintenance export file has not been uploaded yet."
    },
    "hr": {
      "status": "غير متوفر",
      "message": "HR export file has not been uploaded yet."
    },
    "finance": {
      "status": "غير متوفر",
      "message": "Finance export file has not been uploaded yet."
    },
    "licenses": {
      "status": "غير متوفر",
      "message": "Licenses export file has not been uploaded yet."
    }
  }
};
